name: White Paper
markdown: redcarpet
pygments: true
url: cadamei.net
paginate: 8
description:    My project flotsam
intro: A roll of posts relating to anything from gardening to antenna theory, mostly amateur radio
logo:             logo.png
disqus_shortname:
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           Johnathan Staverman
  avatar:         <avatar-image-link>
  email:          js@cadamei.net
  # Social networking links used in footer. Update and remove as you like.
  twitter:cadamei
  github:cadamei
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
