# Site settings
title: Really Amateur Radio
email: js@cadamei.net
description: > # this means to ignore newlines until "baseurl:"
  A roll of posts relating to anything from gardening to antenna theory
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cadamei.github.io" # the base hostname & protocol for your site
twitter_username: cadamei
github_username:  cadamei

# Build settings
markdown: kramdown
